arqua/arqua/urls.py
# -*- coding: utf-8 -*-
"""Django URL root configuration."""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
import private_storage.urls

from userprofiles import views as userprofiles_views


urlpatterns = [
    url(r'^userprofiles/', include('userprofiles.urls')),
    url(r'^videohosting/', include('videohosting.urls')),
    url(r'^telechat/', include('telechat.urls')),
    url(r'^admin/', admin.site.urls),

    url(
        r'^accounts/register/$',
        userprofiles_views.RegistrationView.as_view(),
        name='register'
    ),
    url(
        r'^accounts/login/$',
        userprofiles_views.LoginView.as_view(),
        name='login'
    ),
    url(
        r'^accounts/logout/$',
        userprofiles_views.LogoutView.as_view(),
        name='logout'
    ),
    url(
        r'^accounts/password-change/$',
        userprofiles_views.PasswordChangeView.as_view(),
        name='password_change'
    ),
    url(
        r'^accounts/password-change/done$',
        userprofiles_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    url(r'^api-auth/', include('rest_framework.urls')),
]
urlpatterns += [
    url(r'^$', RedirectView.as_view(pattern_name='videohosting:video_recent'),
        name='index')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url('^private-media/', include(private_storage.urls)),
]

arqua/userprofiles/urls.py
# -*- coding: utf-8 -*-
"""Django configuration for application `userprofiles`."""
from django.conf.urls import url, include

from userprofiles import views, api


app_name = 'userprofiles'
urlpatterns = [
    url(r'^user/(?P<pk>[0-9]*)$', views.UserProfileView.as_view(),
        name='user'),
    url(r'^user_current$', views.view_user_profile_current,
        name='user_current'),
    url(r'^api/', include(api.router.urls)),
]

arqua/videohosting/urls.py
# -*- coding: utf-8 -*-
"""Django URL configuration for `videohosting`."""
from django.conf.urls import url, include
from django.views.generic import RedirectView

from videohosting import views, api


app_name = 'videohosting'
urlpatterns = [
    url(r'^video_recent$', views.VideoRecentView.as_view(),
        name='video_recent'),
    url(r'^video_search$', views.VideoSearchView.as_view(),
        name='video_search'),
    url(r'^video_file/(?P<pk>[0-9]+)$', views.VideoFileDownloadView.as_view(),
        name='video_file'),
    url(r'^video_poster/(?P<pk>[0-9]+)$',
        views.VideoFileDownloadView.as_view(),
        name='video_poster'),
    url(r'^video/(?P<pk>[0-9]+)$', views.VideoView.as_view(), name='video'),
    url(r'^video_edit/(?P<pk>[0-9]+)$', views.VideoEditView.as_view(),
        name='video_edit'),
    url(r'^video_create$', views.VideoCreateView.as_view(),
        name='video_create'),
    url(r'^$', RedirectView.as_view(pattern_name='videohosting:video_recent'),
        name='index'),
    url(r'^api/', include(api.router.urls)),
]

arqua/videohosting/models.py
# -*- coding: utf-8 -*-
"""Django DB models for `videohosting`."""
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import conditional_escape
import private_storage.fields
from rest_framework import (
    decorators, filters, pagination, parsers, permissions, response,
    serializers, status, viewsets
)
import django_filters.rest_framework as drf_filters

from userprofiles.models import (
    UserProfile, UserProfileSerializer,
    get_user_profile_current_object, get_user_profile_object_from_user
)


class Video(models.Model):
    """Video."""

    video_name = models.CharField(
        'Название', max_length=512
    )
    description = models.TextField(
        blank=True, verbose_name='Описание'
    )
    author = models.ForeignKey(
        UserProfile, verbose_name='Автор', null=True,
        on_delete=models.SET_NULL
    )
    video_file = private_storage.fields.PrivateFileField(
        upload_to='protected/videos/', verbose_name='Файл', null=True,
        content_types=['video/mp4', 'video/webm'],
        blank=True
    )
    poster = private_storage.fields.PrivateFileField(
        upload_to='protected/video_posters/', verbose_name='Обложка',
        null=True,
        content_types=[
            'image/png', 'image/jpeg', 'image/bmp', 'image/svg+xml'
        ]
    )
    pub_time = models.DateTimeField(
        'Время отправки', null=True, default=timezone.now, blank=True
    )
    likes = models.ManyToManyField(
        UserProfile, verbose_name='Лайкнувшие', related_name='liked_videos',
        blank=True
    )

    STATUS_PUBLIC = 'PUBLIC'
    STATUS_RESTRICTED = 'RESTRICTED'
    STATUS_BANNED = 'BANNED'
    restrictions = models.CharField('Уровень доступа',
                                    max_length=64,
                                    default=STATUS_PUBLIC,
                                    choices=[
                                        (STATUS_PUBLIC, 'Доступно всем'),
                                        (STATUS_RESTRICTED,
                                         'Ограниченный доступ'),
                                        (STATUS_BANNED, 'Заблокировано'),
                                    ])

    def detail_url(self):
        """Return URL of API method to get video data."""
        return reverse('videohosting:video-detail', args=[self.pk])

    def like_url(self):
        """Return URL of API method to like this video."""
        return reverse('videohosting:video-like', args=[self.pk])

    def unlike_url(self):
        """Return URL of API method to remove like from this video."""
        return reverse('videohosting:video-unlike', args=[self.pk])

    def get_absolute_url(self):
        """Return URL of video."""
        return reverse('videohosting:video', args=(self.pk, ))

    def __str__(self):
        """Return string representation."""
        return '#{} {}'.format(self.pk, self.video_name)

    class Meta:
        """Metaclass."""

        verbose_name = 'видеоролик'
        verbose_name_plural = 'видеоролики'
        permissions = (
            ('can_watch_restricted',
             'Может смотреть видеоролики с ограниченным доступом'),
            ('can_watch_banned', 'Может смотреть заблокированные видеоролики'),
            ('can_add_video_likes', 'Может ставить лайки к видеороликам'),
        )


def restrict_videos(qs, request):
    """Exclude from queryset videos which user can not view."""
    if not request.user.has_perm('videohosting.can_watch_restricted'):
        qs = qs.exclude(restrictions=Video.STATUS_RESTRICTED)
    if not request.user.has_perm('videohosting.can_watch_banned'):
        qs = qs.exclude(restrictions=Video.STATUS_BANNED)
    exclude_filter = models.Q(video_file='')
    if request.user.is_authenticated:
        exclude_filter &= ~models.Q(author__user=request.user)
    qs = qs.exclude(exclude_filter)
    return qs


def get_video_access(obj, request):
    """Return `True` if user has right to view video, otherwise `False`."""
    if obj.restrictions == Video.STATUS_RESTRICTED:
        return request.user.has_perm('videohosting.can_watch_restricted')
    if obj.restrictions == Video.STATUS_BANNED:
        return request.user.has_perm('videohosting.can_watch_banned')
    return True


class VideoSerializer(serializers.ModelSerializer):
    """Serializer for `Video`."""

    author = UserProfileSerializer(read_only=True)
    absolute_url = serializers.CharField(
        source='get_absolute_url', read_only=True
    )
    is_liked = serializers.SerializerMethodField()

    def get_is_liked(self, obj):
        """Return `True` if request user is subscribed to `obj`."""
        request_user = self.context['request'].user
        return bool(obj.likes.filter(user__pk=request_user.pk))

    class Meta:
        """Metaclass."""

        model = Video
        fields = (
            'pk', 'video_name', 'description', 'author', 'absolute_url',
            'pub_time', 'video_file', 'poster', 'is_liked'
        )
        read_only_fields = (
            'author', 'pub_time'
        )


class VideoAPIPermissions(permissions.BasePermission):
    """Permissions for `Video` view set."""

    def has_object_permission(self, request, view, obj):
        """Return `True` if permission is granted, `False` otherwise."""
        if not get_video_access(obj, request):
            return False

        if view.action in ['like', 'unlike']:
            if not request.user or (not request.user.is_authenticated):
                return False
            return request.user.has_perm('videohosting.can_add_video_likes')

        return False


class VideoViewSet(viewsets.ModelViewSet):
    """View set for `Video`."""

    queryset = Video.objects.all()
    serializer_class = VideoSerializer
    permission_classes = (VideoAPIPermissions | permissions.IsAdminUser,)

    def get_queryset(self):
        """Return queryset for view set."""
        return restrict_videos(Video.objects.all(), self.request)

    @decorators.action(detail=True, methods=('put',))
    def upload(
        self, request, pk=None, parser_classes=(parsers.FileUploadParser,)
    ):
        """Upload video file."""
        if 'video_file' not in request.FILES:
            return response.Response({}, status=status.HTTP_400_BAD_REQUEST)
        video_file = request.FILES['video_file']
        video = self.get_object()
        video.video_file = video_file
        video.save()
        return response.Response({})

    @decorators.action(detail=True, methods=('post',))
    def like(self, request, pk=None):
        """Add like from request user to this video."""
        video = self.get_object()
        video.likes.add(
            get_user_profile_object_from_user(request.user)
        )
        video.save()
        serializer = self.get_serializer(video)
        return response.Response(serializer.data)

    @decorators.action(detail=True, methods=('post',))
    def unlike(self, request, pk=None):
        """Remove like from request user to this video."""
        video = self.get_object()
        video.likes.remove(
            get_user_profile_object_from_user(request.user)
        )
        video.save()
        serializer = self.get_serializer(video)
        return response.Response(serializer.data)


class VideoComment(models.Model):
    """Comment for video."""

    author = models.ForeignKey(UserProfile,
                               verbose_name='Автор',
                               null=True,
                               on_delete=models.SET_NULL)
    text = models.TextField('Текст')
    pub_time = models.DateTimeField('Время отправки',
                                    null=True,
                                    default=timezone.now,
                                    blank=True)
    video = models.ForeignKey(Video,
                              verbose_name='Видеоролик',
                              null=True,
                              on_delete=models.CASCADE)
    is_deleted = models.BooleanField(verbose_name='Удалено', default=False,
                                     blank=True)

    def __str__(self):
        """Return string representation."""
        return '#{} к видео {}'.format(self.pk, self.video)

    class Meta:
        """Metaclass."""

        verbose_name = 'комментарий к видеоролику'
        verbose_name_plural = 'комментарии к видеороликам'
        permissions = (
            ('can_add_video_comments',
             'Может добавлять комментарии к видеороликам'),
        )


class VideoCommentSerializer(serializers.ModelSerializer):
    """Serializer for `VideoComment`."""

    author = UserProfileSerializer(read_only=True)
    video = serializers.PrimaryKeyRelatedField(
        many=False, queryset=Video.objects.all(), required=True
    )

    def to_internal_value(self, data):
        data = super(VideoCommentSerializer, self).to_internal_value(data)
        if self.instance:
            for x in self.create_only_fields:
                data.pop(x)
        return data

    def validate(self, data):
        """Validate serialization data."""
        if self.context['view'].action in ['create']:
            if 'author' not in data:
                data['author'] = get_user_profile_current_object(
                    self.context['request']
                )
        data['text'] = conditional_escape(data['text'])
        return data

    class Meta:
        """Metaclass."""

        model = VideoComment
        fields = (
            'pk', 'pub_time', 'author', 'text', 'video'
        )
        read_only_fields = ('pub_time', 'author')
        create_only_fields = ('video',)



arqua/videohosting/forms.py
# -*- coding: utf-8 -*-
"""Django forms for `videohosting`."""
from django import forms

from arqua.utils import form_with_helper
from videohosting.models import Video


@form_with_helper
class VideoCreateForm(forms.ModelForm):
    """Form for creating video (without uploading file)."""

    class Meta:
        """Metaclass."""

        model = Video
        fields = ['video_name', 'description', 'poster']

arqua/videohosting/templates/videohosting/base.html
{% extends 'base.html' %}

{% block menu_local %}
{% if perms.videohosting.add_video %}
<div class="navigation-menu-element">
    видеохостинг:
</div>
<div class="navigation-menu-element">
    <a href="{% url 'videohosting:video_create' %}">[добавление видео]</a>
</div>
{% endif %}
{% endblock %}

arqua/videohosting/templates/videohosting/video.html
{% extends 'videohosting/base.html' %}

{% block content %}
{% load videohosting_extras %}
<article>
	<div class="video-player">
		<video controls id="videoplayer" poster="{% url 'videohosting:video_poster' object.pk %}" volume="">
			<source src="{% url 'videohosting:video_file' object.pk %}" type="video/mp4" />{# TODO #}
			Браузер не поддерживает video.
		</video>
	</div>
	<div>
		<h2>{{ object.video_name }} <strong>[# {{ object.pk }}]</strong></h2>
		<p>
			Добавил <a href="{% url 'userprofiles:user' object.author.pk %}">{{ object.author.user.username }}</a>
			{# TODO: author subscription #}
		</p>
	    <p>{{ object.description }}</p>
		<p>
			<span id="video-field-likes-count">{{ object.likes_count }}</span>
			{% if can_like %}
				<button id="video-unlike-button" {% if not user|is_liker:object %}style="display: none;"{% endif %}>
						Видео лайкнуто (отменить лайк)
				</button>
				<button id="video-like-button" {% if user|is_liker:object %}style="display: none;"{% endif %}>
						Видео не лайкнуто (поставить лайк)
				</button>
			{% endif %}
			</span>
		</p>
	</div>
	
	<h2>
		Комментарии
	</h2>
	<div class="table-responsive">
		<table class="table-list">
			<thead>
				<th scope="col">
					Дата
				</th>
				<th scope="col">
					Автор
				</th>
				<th scope="col">
					Сообщение
				</th>
			</thead>
			<tbody id="video-comments-list">
			</tbody>
		</table>
	</div>
	{% if can_comment %}
	<div>
		<h2>
			Добавление комментария
		</h2>
		<div>
			<textarea class="form-control" id="video-comment-add-text" style="width: 100%;"></textarea>
			<div>
				<button id="video-comment-add-button">Отправить</button>
			</div>
		</div>
	</div>
	{% endif %}
</article>
{% endblock %}

{% block misc %}
<script>
"use strict";

document.modulesLoaded['video'] = false;

var videoPK = Number("{{ object.pk }}");
var refreshTime = 500;

function videoDataAjaxResult(result)
{
	var isLiked = result.is_liked;
	if (isLiked)
	{
		$('#video-like-button').hide();
		$('#video-unlike-button').show();
	}
	else
	{
		$('#video-like-button').show();
		$('#video-unlike-button').hide();
	}
}

function videoGetData()
{
	ajaxGet(
		"{{ object.detail_url }}",
		{},
		videoDataAjaxResult
	);
}

function videoLikeAjaxResult(result)
{
	videoDataAjaxResult(result);
}

function videoLike(e)
{
	e.preventDefault();

	ajaxPost(
		"{{ object.like_url }}",
		{},
		videoLikeAjaxResult
	);
}

function videoUnlikeAjaxResult(result)
{
	videoDataAjaxResult(result);
}

function videoUnlike(e)
{
	e.preventDefault();

	ajaxPost(
		"{{ object.unlike_url }}",
		{},
		videoUnlikeAjaxResult
	);
}

function displayVideoComment(message)
{
	for (var i in videoCommentsElementsArray)
	{
		var videoCommentElement = $(videoCommentsElementsArray[i]);
		if (message.pk == videoCommentElement.data('pk'))
		{
			return;
		}
	}

	var videoCommentsElements = $('#video-comments-list');
	var videoCommentsElementsArray = videoCommentsElements.children().toArray();

	var pubTimeCell = $('<th scope="row"></th>')
		.text(message.pub_time);
	var authorCell = $('<th scope="row"></th>')
		.append(getUserElement(message.author));
	var textCell = $('<td></td>').text(message.text);
	var messageRow = $('<tr></tr>')
		.append(pubTimeCell)
		.append(authorCell)
		.append(textCell)
		.data('pubTime', message.pub_time)
		.data('pk', message.pk);

	if (videoCommentsElementsArray.length > 0)
	{
		$(videoCommentsElementsArray).first().before(messageRow);
	}
	else
	{
		videoCommentsElements.append(messageRow);
	}
}

function sortVideoComments()
{
	var videoCommentsElements = $('#video-comments-list');
	sortChildren(videoCommentsElements, (a, b) =>
		$(a).data('pubTime') > $(b).data('pubTime')
		? 1 : -1);
}

function videoCommentsAjaxResult(result)
{
	var messages = null;
	if ($.isArray(result))
	{
		messages = result;
	}
	else
	{
		messages = result.results;
	}
	for (var i in messages)
	{
		displayVideoComment(messages[i]);
	}
	sortVideoComments();
}

function videoCommentsAjaxResultFunc(callback)
{
	return function (result)
	{
		videoCommentsAjaxResult(result);
		callback();
	}
}

function videoCommentsGetRecent(callback, limit=10)
{
	ajaxGet(
		"{% url 'videohosting:videocomment-list' %}",
		{
			'limit': limit,
			'ordering': '-pub_time',
			'video': videoPK
		},
		videoCommentsAjaxResultFunc(callback)
	);
}

function videoCommentsGetAfterNewest()
{
	var videoCommentsElements = $('#video-comments-list').children();
	if (videoCommentsElements.length == 0)
	{
		videoCommentsGetRecent(emptyFunc);
	}
	else
	{
		var newestPubTime = videoCommentsElements.last().data('pubTime');

		ajaxGet(
			"{% url 'videohosting:videocomment-list' %}",
			{
				'pub_time_after': newestPubTime,
				'ordering': '-pub_time',
				'video': videoPK
			},
			videoCommentsAjaxResult
		);
	}
}

function videoCommentsGetBeforeOldest(limit=10)
{
	var videoCommentsElements = $('#video-comments-list').children();
	if (videoCommentsElements.length == 0)
	{
		videoCommentsGetRecent(emptyFunc);
	}
	else
	{
		var oldestPubTime = videoCommentsElements.first().data('pubTime');

		ajaxGet(
			"{% url 'videohosting:videocomment-list' %}",
			{
				'pub_time_before': oldestPubTime,
				'ordering': '-pub_time',
				'limit': limit,
				'video': videoPK
			},
			videoCommentsAjaxResult
		);
	}
}

function videoCommentAddAjaxResult(result)
{
	videoCommentsGetAfterNewest();
}

function videoCommentAdd(e)
{
	e.preventDefault();

	var messageText = $('#video-comment-add-text').val();
	if (messageText.length > 250)
	{
		$('#video-comment-add-text').val(messageText.substr(0, 1000));
	}
	else
	{
		ajaxPost(
			"{% url 'videohosting:videocomment-list' %}",
			{
				'text': messageText,
				'video': videoPK
			},
			videoCommentAddAjaxResult
		);
  		$('#video-comment-add-text').val('');
	}
}

function timerFunc()
{
	videoCommentsGetAfterNewest();
	setTimeout(timerFunc, refreshTime);
}

function videoInit()
{
	$('#video-comment-add-button').click(videoCommentAdd);
	$('#video-like-button').click(videoLike);
	$('#video-unlike-button').click(videoUnlike);

	videoCommentsGetRecent(function()
	{
		moduleLoaded('video');
		timerFunc();
	}
	);
}

$(document).ready(videoInit);
</script>
{% endblock %}

{# TODO: load some messages when rendering template #}

arqua/videohosting/templates/videohosting/video_create.html
{% extends 'videohosting/base.html' %}

{% block content %}
{% include 'snippets/form.html' with submit_name='Добавить' %}
{% endblock %}

arqua/videohosting/templates/videohosting/video_edit.html
{% extends 'videohosting/base.html' %}

{% block content %}
<style>
.custom-file-input ~ .custom-file-label::after {
    content: "Обзор...";
}
</style>
{% if not object.video_file %}
{# TODO #}
<article>
	<h2>Загрузка файла</h2>
	<form enctype="multipart/form-data" id="video-file-upload-form">
		<div class="input-item">
			<input type="file" class="custom-file-input" name="video_file" id="video-file" accept="video/*" />
		</div>
		<div class="input-item">
			<button class="btn btn-outline-secondary" type="button" id="video-file-upload-button">Загрузить</button>
		</div>
		<div class="input-item">
			<progress id="video-file-upload-progress" value="0" max="100"></div>
		</div>
	</form>
</article>
{% endif %}
{% endblock %}

{% block misc %}
<script>
"use strict";

document.modulesLoaded['videoEdit'] = false;

function videoFileUploadAjaxResult(result)
{
	location.assign("{{ object.get_absolute_url }}");
}

function videoFileUploadProgress(e)
{
	if (e.lengthComputable)
	{
		$('#video-file-upload-progress').attr({
			'value': e.loaded,
			'max': e.total,
		}).css({'width': '' + (100 * e.loaded / e.total) + '%'});
	}
}

function videoFileUpload()
{
	$('#video-file-upload-progress').attr({
		'value': 0,
	});

	var miscParams = {
		cache: false,
		contentType: false,
		processData: false,

		xhr: function()
		{
			var myXhr = $.ajaxSettings.xhr();
			if (myXhr.upload)
			{
				myXhr.upload.addEventListener('progress', videoFileUploadProgress, false);
			}
			return myXhr;
		},
	};
	ajaxPut("{% url 'videohosting:video-upload' object.pk %}", new FormData($('#video-file-upload-form')[0]), videoFileUploadAjaxResult, undefined, miscParams);
}

function videoEditInit()
{
	$('#video-file-upload-button').click(videoFileUpload);

	moduleLoaded('videoEdit');
}

$(document).ready(videoEditInit);
</script>
{% endblock %}

arqua/videohosting/templates/videohosting/video_recent.html
{% extends 'videohosting/base.html' %}

{% block content %}
{% include 'videohosting/snippets/video_list.html' %}
{% endblock %}

arqua/videohosting/templates/videohosting/video_search.html
{% extends 'videohosting/base.html' %}

{% block content %}
{% include 'videohosting/snippets/video_list.html' %}
{% endblock %}